FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o bin/smtp-server ./cmd/smtp-server

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/bin/smtp-server ./smtp-server

EXPOSE 2525

CMD ["./smtp-server"]
